### ISSUE TITLE
aberowl seems to now lowercase labels

### ISSUE THREAD

**Issue by debuos512** [reality/komenti#13]
this causes certain labels to fail to return when properly capitalised 

e.g. http://www.aber-owl.net/api/dlquery/?type=subeq&labels=true&query=JRCNM01005a&offset=1&ontology=ENM
v.s. http://www.aber-owl.net/api/dlquery/?type=subeq&labels=true&query=jrcnm01005a&offset=1&ontology=ENM

**Comment by debuos512** [comment]
(currently lower-casing query as workaround, will open issue on aberowl github)

**Comment by egonw** [comment]
oh, sigh... I should have tried that. Yes, I had seen the lower-case things. Silly of me not to make the link :(

**Comment by egonw** [comment]
BTW, the reason I asked is what I wrote in the deliverable: this is what I did as a proof of principle last year with the ContentMine software, with this as result: https://tools.wmflabs.org/scholia/topic/Q47461491
