### ISSUE TITLE
commons-beanutils 1.8.0 cannot be found

### ISSUE THREAD

**Issue by egonw** [reality/komenti#2]
I tried to run the code but I get this error:

```shell
./Komenti 
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during conversion: Error grabbing Grapes -- [download failed: commons-beanutils#commons-beanutils;1.8.0!commons-beanutils.jar]
```

I tried more recent versions of `commons-cli`, `commons-lang3` , and `stanford-corenlp`, but none solved the problem.

**Comment by debuos512** [comment]
could you please post the output of the following command:

```bash
$ grape --verbose install commons-beanutils commons-beanutils 1.8.0
```

**Comment by egonw** [comment]
Thanks for that command! It told me I did have a copy (partial output):

```
file:/home/egonw/.m2/repository/commons-beanutils/commons-beanutils/1.8.0/commons-beanutils-1.8.0.jar
```

That had to mean that the copy I had was corrupt. I deleted that folder and the folder copy Groovy made into `/home/egonw/.groovy` and that did the job.
