### ISSUE TITLE
next issue: example code throws error

### ISSUE THREAD

**Issue by egonw** [reality/komenti#3]
Okay, thank for getting me started. I was able to successfully run the first example. I immediately see some missing info in the ontology :)

The next example throws an Exception. Likely something on my side again, but I'm not seeing what I do wrong:

```
$ ./Komenti query -o ENM -cl toxicity,asbestos --out labels.txt

Received null labels from 0 classes, for query "l".
Caught: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.io.File(java.lang.Boolean)
groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.io.File(java.lang.Boolean)
        at Komenti.run(Komenti:140)
        at Komenti$run.callCurrent(Unknown Source)
        at Komenti.run(Komenti:52)
```

**Comment by debuos512** [comment]
the argument should be '-c', not '-cl'. it was incorrectly reported in the nanocommons report: have repaired it!
